/**
 * Centralized Error Codes for Backend API
 *
 * These codes are returned to the frontend, which translates them
 * to user-friendly messages based on the selected language.
 *
 * Naming convention: MODULE_ACTION_DESCRIPTION
 */

// ============================================================================
// COMMON / GENERIC ERRORS
// ============================================================================
export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_DATA: 'INVALID_DATA',
  INVALID_ID: 'INVALID_ID',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  // ============================================================================
  // AUTH MODULE
  // ============================================================================
  AUTH_CREDENTIALS_REQUIRED: 'AUTH_CREDENTIALS_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_TOKEN_MISSING: 'AUTH_REFRESH_TOKEN_MISSING',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_USER_NOT_AUTHENTICATED: 'AUTH_USER_NOT_AUTHENTICATED',
  AUTH_NO_IMAGE_PROVIDED: 'AUTH_NO_IMAGE_PROVIDED',
  AUTH_INVALID_FILE_TYPE: 'AUTH_INVALID_FILE_TYPE',
  AUTH_CURRENT_PASSWORD_INCORRECT: 'AUTH_CURRENT_PASSWORD_INCORRECT',
  AUTH_FETCH_USERS_ERROR: 'AUTH_FETCH_USERS_ERROR',
  AUTH_FETCH_USER_ERROR: 'AUTH_FETCH_USER_ERROR',
  AUTH_FETCH_USERS_BY_ROLE_ERROR: 'AUTH_FETCH_USERS_BY_ROLE_ERROR',
  AUTH_UPDATE_USER_ERROR: 'AUTH_UPDATE_USER_ERROR',
  AUTH_DELETE_USER_ERROR: 'AUTH_DELETE_USER_ERROR',
  AUTH_UPLOAD_AVATAR_ERROR: 'AUTH_UPLOAD_AVATAR_ERROR',
  AUTH_DELETE_AVATAR_ERROR: 'AUTH_DELETE_AVATAR_ERROR',

  // ============================================================================
  // BACKOFFICE MODULE
  // ============================================================================
  BACKOFFICE_COST_CENTER_DEPARTMENT_REQUIRED: 'BACKOFFICE_COST_CENTER_DEPARTMENT_REQUIRED',
  BACKOFFICE_NAME_REQUIRED: 'BACKOFFICE_NAME_REQUIRED',
  BACKOFFICE_SUPPLIER_EXISTS: 'BACKOFFICE_SUPPLIER_EXISTS',
  BACKOFFICE_SUPPLIER_INACTIVE_EXISTS: 'BACKOFFICE_SUPPLIER_INACTIVE_EXISTS',
  BACKOFFICE_SUPPLIER_HAS_INVOICES: 'BACKOFFICE_SUPPLIER_HAS_INVOICES',
  BACKOFFICE_INVOICE_FIELDS_REQUIRED: 'BACKOFFICE_INVOICE_FIELDS_REQUIRED',
  BACKOFFICE_SUPPLIER_NOT_FOUND: 'BACKOFFICE_SUPPLIER_NOT_FOUND',
  BACKOFFICE_REJECTION_REASON_REQUIRED: 'BACKOFFICE_REJECTION_REASON_REQUIRED',
  BACKOFFICE_PAYMENT_DATE_REQUIRED: 'BACKOFFICE_PAYMENT_DATE_REQUIRED',
  BACKOFFICE_NO_FILE_SENT: 'BACKOFFICE_NO_FILE_SENT',
  BACKOFFICE_PDF_ONLY: 'BACKOFFICE_PDF_ONLY',
  BACKOFFICE_FILE_TOO_LARGE: 'BACKOFFICE_FILE_TOO_LARGE',
  BACKOFFICE_INVALID_ASSET_TYPE: 'BACKOFFICE_INVALID_ASSET_TYPE',
  BACKOFFICE_NO_IMAGE_SENT: 'BACKOFFICE_NO_IMAGE_SENT',
  BACKOFFICE_INVALID_IMAGE_TYPE: 'BACKOFFICE_INVALID_IMAGE_TYPE',
  BACKOFFICE_INVOICE_IDS_REQUIRED: 'BACKOFFICE_INVOICE_IDS_REQUIRED',
  BACKOFFICE_MAX_INVOICES_EXCEEDED: 'BACKOFFICE_MAX_INVOICES_EXCEEDED',
  BACKOFFICE_PDF_TYPE_REQUIRED: 'BACKOFFICE_PDF_TYPE_REQUIRED',
  BACKOFFICE_INVALID_MONTH: 'BACKOFFICE_INVALID_MONTH',
  BACKOFFICE_YEAR_MONTH_REQUIRED: 'BACKOFFICE_YEAR_MONTH_REQUIRED',
  BACKOFFICE_CATEGORY_NOT_FOUND: 'BACKOFFICE_CATEGORY_NOT_FOUND',
  BACKOFFICE_INVOICE_NOT_FOUND: 'BACKOFFICE_INVOICE_NOT_FOUND',
  BACKOFFICE_INVOICE_NOT_VALIDATED: 'BACKOFFICE_INVOICE_NOT_VALIDATED',
  BACKOFFICE_INVOICES_NOT_FOUND: 'BACKOFFICE_INVOICES_NOT_FOUND',
  BACKOFFICE_ASSET_NOT_FOUND: 'BACKOFFICE_ASSET_NOT_FOUND',
  BACKOFFICE_FETCH_CATEGORIES_ERROR: 'BACKOFFICE_FETCH_CATEGORIES_ERROR',
  BACKOFFICE_FETCH_CATEGORY_ERROR: 'BACKOFFICE_FETCH_CATEGORY_ERROR',
  BACKOFFICE_CREATE_CATEGORY_ERROR: 'BACKOFFICE_CREATE_CATEGORY_ERROR',
  BACKOFFICE_FETCH_SUPPLIERS_ERROR: 'BACKOFFICE_FETCH_SUPPLIERS_ERROR',
  BACKOFFICE_FETCH_SUPPLIER_ERROR: 'BACKOFFICE_FETCH_SUPPLIER_ERROR',
  BACKOFFICE_CREATE_SUPPLIER_ERROR: 'BACKOFFICE_CREATE_SUPPLIER_ERROR',
  BACKOFFICE_UPDATE_SUPPLIER_ERROR: 'BACKOFFICE_UPDATE_SUPPLIER_ERROR',
  BACKOFFICE_DEACTIVATE_SUPPLIER_ERROR: 'BACKOFFICE_DEACTIVATE_SUPPLIER_ERROR',
  BACKOFFICE_INACTIVATE_SUPPLIER_ERROR: 'BACKOFFICE_INACTIVATE_SUPPLIER_ERROR',
  BACKOFFICE_ACTIVATE_SUPPLIER_ERROR: 'BACKOFFICE_ACTIVATE_SUPPLIER_ERROR',
  BACKOFFICE_DELETE_SUPPLIER_ERROR: 'BACKOFFICE_DELETE_SUPPLIER_ERROR',
  BACKOFFICE_FETCH_INVOICES_ERROR: 'BACKOFFICE_FETCH_INVOICES_ERROR',
  BACKOFFICE_FETCH_INVOICE_ERROR: 'BACKOFFICE_FETCH_INVOICE_ERROR',
  BACKOFFICE_CREATE_INVOICE_ERROR: 'BACKOFFICE_CREATE_INVOICE_ERROR',
  BACKOFFICE_UPDATE_INVOICE_ERROR: 'BACKOFFICE_UPDATE_INVOICE_ERROR',
  BACKOFFICE_VALIDATE_INVOICE_ERROR: 'BACKOFFICE_VALIDATE_INVOICE_ERROR',
  BACKOFFICE_REJECT_INVOICE_ERROR: 'BACKOFFICE_REJECT_INVOICE_ERROR',
  BACKOFFICE_REVERT_VALIDATION_ERROR: 'BACKOFFICE_REVERT_VALIDATION_ERROR',
  BACKOFFICE_MARK_PAID_ERROR: 'BACKOFFICE_MARK_PAID_ERROR',
  BACKOFFICE_DELETE_INVOICE_ERROR: 'BACKOFFICE_DELETE_INVOICE_ERROR',
  BACKOFFICE_FETCH_HISTORY_ERROR: 'BACKOFFICE_FETCH_HISTORY_ERROR',
  BACKOFFICE_UPLOAD_PDF_ERROR: 'BACKOFFICE_UPLOAD_PDF_ERROR',
  BACKOFFICE_FETCH_ASSETS_ERROR: 'BACKOFFICE_FETCH_ASSETS_ERROR',
  BACKOFFICE_CREATE_ASSET_ERROR: 'BACKOFFICE_CREATE_ASSET_ERROR',
  BACKOFFICE_DELETE_ASSET_ERROR: 'BACKOFFICE_DELETE_ASSET_ERROR',
  BACKOFFICE_SET_DEFAULT_ERROR: 'BACKOFFICE_SET_DEFAULT_ERROR',
  BACKOFFICE_CREATE_ZIP_ERROR: 'BACKOFFICE_CREATE_ZIP_ERROR',
  BACKOFFICE_GET_PDF_URL_ERROR: 'BACKOFFICE_GET_PDF_URL_ERROR',
  BACKOFFICE_DOWNLOAD_PDF_ERROR: 'BACKOFFICE_DOWNLOAD_PDF_ERROR',
  BACKOFFICE_FETCH_STATS_ERROR: 'BACKOFFICE_FETCH_STATS_ERROR',
  BACKOFFICE_FETCH_MONTHLY_SUMMARY_ERROR: 'BACKOFFICE_FETCH_MONTHLY_SUMMARY_ERROR',
  BACKOFFICE_BATCH_PAYMENT_PREVIEW_ERROR: 'BACKOFFICE_BATCH_PAYMENT_PREVIEW_ERROR',
  BACKOFFICE_BATCH_PAYMENT_ERROR: 'BACKOFFICE_BATCH_PAYMENT_ERROR',
  BACKOFFICE_REVERT_BATCH_PREVIEW_ERROR: 'BACKOFFICE_REVERT_BATCH_PREVIEW_ERROR',
  BACKOFFICE_REVERT_BATCH_ERROR: 'BACKOFFICE_REVERT_BATCH_ERROR',

  // ============================================================================
  // BLACKLIST MODULE
  // ============================================================================
  BLACKLIST_INVALID_SEARCH_PARAMS: 'BLACKLIST_INVALID_SEARCH_PARAMS',
  BLACKLIST_DOCUMENT_EXISTS: 'BLACKLIST_DOCUMENT_EXISTS',
  BLACKLIST_NO_IMAGE_SENT: 'BLACKLIST_NO_IMAGE_SENT',
  BLACKLIST_INVALID_FILE_TYPE: 'BLACKLIST_INVALID_FILE_TYPE',
  BLACKLIST_FILE_TOO_LARGE: 'BLACKLIST_FILE_TOO_LARGE',
  BLACKLIST_PUBLIC_ID_MISSING: 'BLACKLIST_PUBLIC_ID_MISSING',
  BLACKLIST_RECORD_NOT_FOUND: 'BLACKLIST_RECORD_NOT_FOUND',
  BLACKLIST_IMAGE_NOT_FOUND: 'BLACKLIST_IMAGE_NOT_FOUND',
  BLACKLIST_FETCH_RECORDS_ERROR: 'BLACKLIST_FETCH_RECORDS_ERROR',
  BLACKLIST_FETCH_RECORD_ERROR: 'BLACKLIST_FETCH_RECORD_ERROR',
  BLACKLIST_CREATE_RECORD_ERROR: 'BLACKLIST_CREATE_RECORD_ERROR',
  BLACKLIST_UPDATE_RECORD_ERROR: 'BLACKLIST_UPDATE_RECORD_ERROR',
  BLACKLIST_DELETE_RECORD_ERROR: 'BLACKLIST_DELETE_RECORD_ERROR',
  BLACKLIST_RESTORE_RECORD_ERROR: 'BLACKLIST_RESTORE_RECORD_ERROR',
  BLACKLIST_FETCH_STATS_ERROR: 'BLACKLIST_FETCH_STATS_ERROR',
  BLACKLIST_UPLOAD_IMAGE_ERROR: 'BLACKLIST_UPLOAD_IMAGE_ERROR',
  BLACKLIST_DELETE_IMAGE_ERROR: 'BLACKLIST_DELETE_IMAGE_ERROR',

  // ============================================================================
  // CASHIER MODULE
  // ============================================================================
  CASHIER_DAY_ALREADY_INITIALIZED: 'CASHIER_DAY_ALREADY_INITIALIZED',
  CASHIER_SHIFTS_ALREADY_EXIST: 'CASHIER_SHIFTS_ALREADY_EXIST',
  CASHIER_INVALID_YEAR_MONTH: 'CASHIER_INVALID_YEAR_MONTH',
  CASHIER_DAY_NOT_FOUND: 'CASHIER_DAY_NOT_FOUND',
  CASHIER_DAY_CANNOT_CLOSE: 'CASHIER_DAY_CANNOT_CLOSE',
  CASHIER_CLOSE_DAY_ERROR: 'CASHIER_CLOSE_DAY_ERROR',
  CASHIER_REOPEN_DAY_ERROR: 'CASHIER_REOPEN_DAY_ERROR',
  CASHIER_SHIFT_NOT_FOUND: 'CASHIER_SHIFT_NOT_FOUND',
  CASHIER_VOUCHER_MAX_REACHED: 'CASHIER_VOUCHER_MAX_REACHED',
  CASHIER_VOUCHER_NOT_FOUND: 'CASHIER_VOUCHER_NOT_FOUND',
  CASHIER_INVALID_SHIFT_ID: 'CASHIER_INVALID_SHIFT_ID',
  CASHIER_INVALID_DATE_FORMAT: 'CASHIER_INVALID_DATE_FORMAT',
  CASHIER_DATE_RANGE_REQUIRED: 'CASHIER_DATE_RANGE_REQUIRED',
  CASHIER_INVALID_DATE_RANGE: 'CASHIER_INVALID_DATE_RANGE',
  CASHIER_FETCH_DAY_ERROR: 'CASHIER_FETCH_DAY_ERROR',
  CASHIER_INIT_DAY_ERROR: 'CASHIER_INIT_DAY_ERROR',
  CASHIER_FETCH_SUMMARY_ERROR: 'CASHIER_FETCH_SUMMARY_ERROR',
  CASHIER_FETCH_DAYS_ERROR: 'CASHIER_FETCH_DAYS_ERROR',
  CASHIER_FETCH_MONTHLY_SUMMARY_ERROR: 'CASHIER_FETCH_MONTHLY_SUMMARY_ERROR',
  CASHIER_FETCH_SHIFT_ERROR: 'CASHIER_FETCH_SHIFT_ERROR',
  CASHIER_FETCH_SHIFTS_ERROR: 'CASHIER_FETCH_SHIFTS_ERROR',
  CASHIER_UPDATE_USERS_ERROR: 'CASHIER_UPDATE_USERS_ERROR',
  CASHIER_FETCH_HISTORY_ERROR: 'CASHIER_FETCH_HISTORY_ERROR',
  CASHIER_FETCH_PAYMENTS_ERROR: 'CASHIER_FETCH_PAYMENTS_ERROR',
  CASHIER_FETCH_PAYMENT_SUMMARY_ERROR: 'CASHIER_FETCH_PAYMENT_SUMMARY_ERROR',
  CASHIER_UPDATE_PAYMENTS_ERROR: 'CASHIER_UPDATE_PAYMENTS_ERROR',
  CASHIER_CREATE_PAYMENT_ERROR: 'CASHIER_CREATE_PAYMENT_ERROR',
  CASHIER_DELETE_PAYMENT_ERROR: 'CASHIER_DELETE_PAYMENT_ERROR',
  CASHIER_FETCH_VOUCHERS_ERROR: 'CASHIER_FETCH_VOUCHERS_ERROR',
  CASHIER_FETCH_ACTIVE_VOUCHERS_ERROR: 'CASHIER_FETCH_ACTIVE_VOUCHERS_ERROR',
  CASHIER_FETCH_VOUCHER_ERROR: 'CASHIER_FETCH_VOUCHER_ERROR',
  CASHIER_CREATE_VOUCHER_ERROR: 'CASHIER_CREATE_VOUCHER_ERROR',
  CASHIER_FETCH_VOUCHER_STATS_ERROR: 'CASHIER_FETCH_VOUCHER_STATS_ERROR',
  CASHIER_FETCH_DENOMINATIONS_ERROR: 'CASHIER_FETCH_DENOMINATIONS_ERROR',
  CASHIER_UPDATE_DENOMINATIONS_ERROR: 'CASHIER_UPDATE_DENOMINATIONS_ERROR',
  CASHIER_CREATE_DENOMINATION_ERROR: 'CASHIER_CREATE_DENOMINATION_ERROR',
  CASHIER_DELETE_DENOMINATION_ERROR: 'CASHIER_DELETE_DENOMINATION_ERROR',
  CASHIER_FETCH_HISTORY_STATS_ERROR: 'CASHIER_FETCH_HISTORY_STATS_ERROR',
  CASHIER_FETCH_SHIFT_HISTORY_ERROR: 'CASHIER_FETCH_SHIFT_HISTORY_ERROR',
  CASHIER_FETCH_RECENT_ACTIVITY_ERROR: 'CASHIER_FETCH_RECENT_ACTIVITY_ERROR',
  CASHIER_FETCH_DASHBOARD_ERROR: 'CASHIER_FETCH_DASHBOARD_ERROR',
  CASHIER_FETCH_DAILY_REPORT_ERROR: 'CASHIER_FETCH_DAILY_REPORT_ERROR',
  CASHIER_FETCH_PERIOD_REPORT_ERROR: 'CASHIER_FETCH_PERIOD_REPORT_ERROR',
  CASHIER_FETCH_VOUCHER_HISTORY_ERROR: 'CASHIER_FETCH_VOUCHER_HISTORY_ERROR',
  CASHIER_FETCH_SHIFT_SUMMARY_ERROR: 'CASHIER_FETCH_SHIFT_SUMMARY_ERROR',

  // ============================================================================
  // CONCILIATION MODULE
  // ============================================================================
  CONCILIATION_INVALID_YEAR_MONTH: 'CONCILIATION_INVALID_YEAR_MONTH',
  CONCILIATION_INVALID_YEAR: 'CONCILIATION_INVALID_YEAR',
  CONCILIATION_INVALID_MONTH: 'CONCILIATION_INVALID_MONTH',
  CONCILIATION_DATE_REQUIRED: 'CONCILIATION_DATE_REQUIRED',
  CONCILIATION_INCOMPLETE_DATA: 'CONCILIATION_INCOMPLETE_DATA',
  CONCILIATION_INVALID_RECEPTION_ENTRIES: 'CONCILIATION_INVALID_RECEPTION_ENTRIES',
  CONCILIATION_INVALID_HOUSEKEEPING_ENTRIES: 'CONCILIATION_INVALID_HOUSEKEEPING_ENTRIES',
  CONCILIATION_INVALID_STATUS: 'CONCILIATION_INVALID_STATUS',
  CONCILIATION_ADMIN_ONLY_CLOSE: 'CONCILIATION_ADMIN_ONLY_CLOSE',
  CONCILIATION_ALREADY_EXISTS: 'CONCILIATION_ALREADY_EXISTS',
  CONCILIATION_CLOSED_CANNOT_MODIFY: 'CONCILIATION_CLOSED_CANNOT_MODIFY',
  CONCILIATION_NOT_FOUND: 'CONCILIATION_NOT_FOUND',
  CONCILIATION_FETCH_ERROR: 'CONCILIATION_FETCH_ERROR',
  CONCILIATION_FETCH_ONE_ERROR: 'CONCILIATION_FETCH_ONE_ERROR',
  CONCILIATION_CREATE_ERROR: 'CONCILIATION_CREATE_ERROR',
  CONCILIATION_UPDATE_FORM_ERROR: 'CONCILIATION_UPDATE_FORM_ERROR',
  CONCILIATION_UPDATE_STATUS_ERROR: 'CONCILIATION_UPDATE_STATUS_ERROR',
  CONCILIATION_RECALCULATE_ERROR: 'CONCILIATION_RECALCULATE_ERROR',
  CONCILIATION_DELETE_ERROR: 'CONCILIATION_DELETE_ERROR',
  CONCILIATION_MONTHLY_FETCH_ERROR: 'CONCILIATION_MONTHLY_FETCH_ERROR',
  CONCILIATION_MONTHLY_VALIDATE_ERROR: 'CONCILIATION_MONTHLY_VALIDATE_ERROR',
  CONCILIATION_MONTHLY_UPDATE_STATUS_ERROR: 'CONCILIATION_MONTHLY_UPDATE_STATUS_ERROR',
  CONCILIATION_MONTHLY_MISSING_DAYS_ERROR: 'CONCILIATION_MONTHLY_MISSING_DAYS_ERROR',

  // ============================================================================
  // DEPARTMENTS MODULE
  // ============================================================================
  DEPARTMENTS_NAME_REQUIRED: 'DEPARTMENTS_NAME_REQUIRED',
  DEPARTMENTS_DUPLICATE: 'DEPARTMENTS_DUPLICATE',
  DEPARTMENTS_HAS_RECORDS: 'DEPARTMENTS_HAS_RECORDS',
  DEPARTMENTS_NOT_FOUND: 'DEPARTMENTS_NOT_FOUND',
  DEPARTMENTS_CREATE_ERROR: 'DEPARTMENTS_CREATE_ERROR',
  DEPARTMENTS_FETCH_ERROR: 'DEPARTMENTS_FETCH_ERROR',
  DEPARTMENTS_FETCH_ONE_ERROR: 'DEPARTMENTS_FETCH_ONE_ERROR',
  DEPARTMENTS_UPDATE_ERROR: 'DEPARTMENTS_UPDATE_ERROR',
  DEPARTMENTS_DELETE_ERROR: 'DEPARTMENTS_DELETE_ERROR',

  // ============================================================================
  // GROUP MODULE
  // ============================================================================
  GROUP_INVALID_ID: 'GROUP_INVALID_ID',
  GROUP_MISSING_REQUIRED_FIELDS: 'GROUP_MISSING_REQUIRED_FIELDS',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_FETCH_ERROR: 'GROUP_FETCH_ERROR',
  GROUP_FETCH_ONE_ERROR: 'GROUP_FETCH_ONE_ERROR',
  GROUP_CREATE_ERROR: 'GROUP_CREATE_ERROR',
  GROUP_UPDATE_ERROR: 'GROUP_UPDATE_ERROR',
  GROUP_DELETE_ERROR: 'GROUP_DELETE_ERROR',
  GROUP_FETCH_DASHBOARD_ERROR: 'GROUP_FETCH_DASHBOARD_ERROR',
  GROUP_FETCH_TIMELINE_ERROR: 'GROUP_FETCH_TIMELINE_ERROR',

  // Group Contact
  GROUP_CONTACT_NOT_FOUND: 'GROUP_CONTACT_NOT_FOUND',
  GROUP_CONTACT_NOT_IN_GROUP: 'GROUP_CONTACT_NOT_IN_GROUP',
  GROUP_CONTACT_PRIMARY_NOT_FOUND: 'GROUP_CONTACT_PRIMARY_NOT_FOUND',
  GROUP_CONTACT_FETCH_ERROR: 'GROUP_CONTACT_FETCH_ERROR',
  GROUP_CONTACT_CREATE_ERROR: 'GROUP_CONTACT_CREATE_ERROR',
  GROUP_CONTACT_UPDATE_ERROR: 'GROUP_CONTACT_UPDATE_ERROR',
  GROUP_CONTACT_DELETE_ERROR: 'GROUP_CONTACT_DELETE_ERROR',
  GROUP_CONTACT_FETCH_PRIMARY_ERROR: 'GROUP_CONTACT_FETCH_PRIMARY_ERROR',

  // Group Room
  GROUP_ROOM_MISSING_FIELDS: 'GROUP_ROOM_MISSING_FIELDS',
  GROUP_ROOM_NOT_FOUND: 'GROUP_ROOM_NOT_FOUND',
  GROUP_ROOM_NOT_IN_GROUP: 'GROUP_ROOM_NOT_IN_GROUP',
  GROUP_ROOM_FETCH_ERROR: 'GROUP_ROOM_FETCH_ERROR',
  GROUP_ROOM_SAVE_ERROR: 'GROUP_ROOM_SAVE_ERROR',
  GROUP_ROOM_UPDATE_ERROR: 'GROUP_ROOM_UPDATE_ERROR',
  GROUP_ROOM_DELETE_ERROR: 'GROUP_ROOM_DELETE_ERROR',

  // Group Payment
  GROUP_PAYMENT_MISSING_FIELDS: 'GROUP_PAYMENT_MISSING_FIELDS',
  GROUP_PAYMENT_INVALID_AMOUNT: 'GROUP_PAYMENT_INVALID_AMOUNT',
  GROUP_PAYMENT_NOT_FOUND: 'GROUP_PAYMENT_NOT_FOUND',
  GROUP_PAYMENT_NOT_IN_GROUP: 'GROUP_PAYMENT_NOT_IN_GROUP',
  GROUP_PAYMENT_FETCH_ERROR: 'GROUP_PAYMENT_FETCH_ERROR',
  GROUP_PAYMENT_CREATE_ERROR: 'GROUP_PAYMENT_CREATE_ERROR',
  GROUP_PAYMENT_UPDATE_ERROR: 'GROUP_PAYMENT_UPDATE_ERROR',
  GROUP_PAYMENT_DELETE_ERROR: 'GROUP_PAYMENT_DELETE_ERROR',

  // Group Status
  GROUP_STATUS_CONFIRMED_REQUIRED: 'GROUP_STATUS_CONFIRMED_REQUIRED',
  GROUP_STATUS_SIGNED_REQUIRED: 'GROUP_STATUS_SIGNED_REQUIRED',
  GROUP_STATUS_NOT_FOUND: 'GROUP_STATUS_NOT_FOUND',
  GROUP_STATUS_FETCH_ERROR: 'GROUP_STATUS_FETCH_ERROR',
  GROUP_STATUS_UPDATE_BOOKING_ERROR: 'GROUP_STATUS_UPDATE_BOOKING_ERROR',
  GROUP_STATUS_UPDATE_CONTRACT_ERROR: 'GROUP_STATUS_UPDATE_CONTRACT_ERROR',
  GROUP_STATUS_UPDATE_ROOMING_ERROR: 'GROUP_STATUS_UPDATE_ROOMING_ERROR',
  GROUP_STATUS_UPDATE_BALANCE_ERROR: 'GROUP_STATUS_UPDATE_BALANCE_ERROR',

  // Group History
  GROUP_HISTORY_FETCH_ERROR: 'GROUP_HISTORY_FETCH_ERROR',

  // ============================================================================
  // LOGBOOK MODULE
  // ============================================================================
  LOGBOOK_INVALID_IMPORTANCE: 'LOGBOOK_INVALID_IMPORTANCE',
  LOGBOOK_NOT_FOUND: 'LOGBOOK_NOT_FOUND',
  LOGBOOK_NOT_SOLVED: 'LOGBOOK_NOT_SOLVED',
  LOGBOOK_ONLY_AUTHOR_DELETE: 'LOGBOOK_ONLY_AUTHOR_DELETE',
  LOGBOOK_ONLY_AUTHOR_UPDATE: 'LOGBOOK_ONLY_AUTHOR_UPDATE',
  LOGBOOK_CREATE_ERROR: 'LOGBOOK_CREATE_ERROR',
  LOGBOOK_FETCH_ERROR: 'LOGBOOK_FETCH_ERROR',
  LOGBOOK_FETCH_BY_DEPARTMENT_ERROR: 'LOGBOOK_FETCH_BY_DEPARTMENT_ERROR',
  LOGBOOK_FETCH_BY_AUTHOR_ERROR: 'LOGBOOK_FETCH_BY_AUTHOR_ERROR',
  LOGBOOK_FETCH_BY_IMPORTANCE_ERROR: 'LOGBOOK_FETCH_BY_IMPORTANCE_ERROR',
  LOGBOOK_FETCH_BY_DAY_ERROR: 'LOGBOOK_FETCH_BY_DAY_ERROR',
  LOGBOOK_DELETE_ERROR: 'LOGBOOK_DELETE_ERROR',

  // Logbook Reads
  LOGBOOK_READ_ERROR: 'LOGBOOK_READ_ERROR',
  LOGBOOK_UNREAD_ERROR: 'LOGBOOK_UNREAD_ERROR',
  LOGBOOK_SOLVE_ERROR: 'LOGBOOK_SOLVE_ERROR',
  LOGBOOK_REOPEN_ERROR: 'LOGBOOK_REOPEN_ERROR',
  LOGBOOK_FETCH_READERS_ERROR: 'LOGBOOK_FETCH_READERS_ERROR',
  LOGBOOK_FETCH_SOLVER_ERROR: 'LOGBOOK_FETCH_SOLVER_ERROR',

  // Logbook Comments
  LOGBOOK_COMMENT_NOT_FOUND: 'LOGBOOK_COMMENT_NOT_FOUND',
  LOGBOOK_COMMENT_NOT_IN_LOGBOOK: 'LOGBOOK_COMMENT_NOT_IN_LOGBOOK',
  LOGBOOK_COMMENT_NO_PERMISSION: 'LOGBOOK_COMMENT_NO_PERMISSION',
  LOGBOOK_COMMENT_CREATE_ERROR: 'LOGBOOK_COMMENT_CREATE_ERROR',
  LOGBOOK_COMMENT_UPDATE_ERROR: 'LOGBOOK_COMMENT_UPDATE_ERROR',
  LOGBOOK_COMMENT_DELETE_ERROR: 'LOGBOOK_COMMENT_DELETE_ERROR',

  // ============================================================================
  // MAINTENANCE MODULE
  // ============================================================================
  MAINTENANCE_INVALID_SEARCH_PARAMS: 'MAINTENANCE_INVALID_SEARCH_PARAMS',
  MAINTENANCE_MAX_IMAGES_REACHED: 'MAINTENANCE_MAX_IMAGES_REACHED',
  MAINTENANCE_NO_IMAGE_SENT: 'MAINTENANCE_NO_IMAGE_SENT',
  MAINTENANCE_INVALID_FILE_TYPE: 'MAINTENANCE_INVALID_FILE_TYPE',
  MAINTENANCE_FILE_TOO_LARGE: 'MAINTENANCE_FILE_TOO_LARGE',
  MAINTENANCE_REPORT_IMAGE_REQUIRED: 'MAINTENANCE_REPORT_IMAGE_REQUIRED',
  MAINTENANCE_IMAGE_NOT_IN_REPORT: 'MAINTENANCE_IMAGE_NOT_IN_REPORT',
  MAINTENANCE_REPORT_NOT_FOUND: 'MAINTENANCE_REPORT_NOT_FOUND',
  MAINTENANCE_IMAGE_NOT_FOUND: 'MAINTENANCE_IMAGE_NOT_FOUND',
  MAINTENANCE_FETCH_REPORTS_ERROR: 'MAINTENANCE_FETCH_REPORTS_ERROR',
  MAINTENANCE_FETCH_REPORT_ERROR: 'MAINTENANCE_FETCH_REPORT_ERROR',
  MAINTENANCE_CREATE_REPORT_ERROR: 'MAINTENANCE_CREATE_REPORT_ERROR',
  MAINTENANCE_UPDATE_REPORT_ERROR: 'MAINTENANCE_UPDATE_REPORT_ERROR',
  MAINTENANCE_UPDATE_STATUS_ERROR: 'MAINTENANCE_UPDATE_STATUS_ERROR',
  MAINTENANCE_UPDATE_PRIORITY_ERROR: 'MAINTENANCE_UPDATE_PRIORITY_ERROR',
  MAINTENANCE_ADD_NOTES_ERROR: 'MAINTENANCE_ADD_NOTES_ERROR',
  MAINTENANCE_ASSIGN_ERROR: 'MAINTENANCE_ASSIGN_ERROR',
  MAINTENANCE_DELETE_REPORT_ERROR: 'MAINTENANCE_DELETE_REPORT_ERROR',
  MAINTENANCE_RESTORE_REPORT_ERROR: 'MAINTENANCE_RESTORE_REPORT_ERROR',
  MAINTENANCE_FETCH_IMAGES_ERROR: 'MAINTENANCE_FETCH_IMAGES_ERROR',
  MAINTENANCE_UPLOAD_IMAGE_ERROR: 'MAINTENANCE_UPLOAD_IMAGE_ERROR',
  MAINTENANCE_DELETE_IMAGE_ERROR: 'MAINTENANCE_DELETE_IMAGE_ERROR',
  MAINTENANCE_FETCH_HISTORY_ERROR: 'MAINTENANCE_FETCH_HISTORY_ERROR',
  MAINTENANCE_FETCH_STATS_ERROR: 'MAINTENANCE_FETCH_STATS_ERROR',

  // ============================================================================
  // MESSAGES MODULE
  // ============================================================================
  MESSAGES_INVALID_CONVERSATION_ID: 'MESSAGES_INVALID_CONVERSATION_ID',
  MESSAGES_INVALID_MESSAGE_ID: 'MESSAGES_INVALID_MESSAGE_ID',
  MESSAGES_MISSING_REQUIRED_FIELDS: 'MESSAGES_MISSING_REQUIRED_FIELDS',
  MESSAGES_DM_ONE_PARTICIPANT: 'MESSAGES_DM_ONE_PARTICIPANT',
  MESSAGES_GROUP_NAME_REQUIRED: 'MESSAGES_GROUP_NAME_REQUIRED',
  MESSAGES_GROUP_NAME_TOO_LONG: 'MESSAGES_GROUP_NAME_TOO_LONG',
  MESSAGES_GROUP_MAX_PARTICIPANTS: 'MESSAGES_GROUP_MAX_PARTICIPANTS',
  MESSAGES_SPECIFY_USER: 'MESSAGES_SPECIFY_USER',
  MESSAGES_EMPTY_MESSAGE: 'MESSAGES_EMPTY_MESSAGE',
  MESSAGES_MESSAGE_TOO_LONG: 'MESSAGES_MESSAGE_TOO_LONG',
  MESSAGES_SEARCH_MIN_LENGTH: 'MESSAGES_SEARCH_MIN_LENGTH',
  MESSAGES_NO_ACCESS: 'MESSAGES_NO_ACCESS',
  MESSAGES_ADMIN_ONLY_EDIT: 'MESSAGES_ADMIN_ONLY_EDIT',
  MESSAGES_GROUPS_ONLY_EDIT: 'MESSAGES_GROUPS_ONLY_EDIT',
  MESSAGES_NOT_PARTICIPANT: 'MESSAGES_NOT_PARTICIPANT',
  MESSAGES_ADMIN_OR_SYSTEM_DELETE: 'MESSAGES_ADMIN_OR_SYSTEM_DELETE',
  MESSAGES_GROUPS_ONLY_ADD: 'MESSAGES_GROUPS_ONLY_ADD',
  MESSAGES_ADMIN_ONLY_ADD: 'MESSAGES_ADMIN_ONLY_ADD',
  MESSAGES_GROUPS_ONLY_REMOVE: 'MESSAGES_GROUPS_ONLY_REMOVE',
  MESSAGES_ADMIN_ONLY_REMOVE: 'MESSAGES_ADMIN_ONLY_REMOVE',
  MESSAGES_USE_LEAVE_OPTION: 'MESSAGES_USE_LEAVE_OPTION',
  MESSAGES_ADMIN_ONLY_VIEW_ALL: 'MESSAGES_ADMIN_ONLY_VIEW_ALL',
  MESSAGES_ONLY_OWN_EDIT: 'MESSAGES_ONLY_OWN_EDIT',
  MESSAGES_ONLY_OWN_DELETE: 'MESSAGES_ONLY_OWN_DELETE',
  MESSAGES_CONVERSATION_NOT_FOUND: 'MESSAGES_CONVERSATION_NOT_FOUND',
  MESSAGES_MESSAGE_NOT_FOUND: 'MESSAGES_MESSAGE_NOT_FOUND',
  MESSAGES_FETCH_CONVERSATIONS_ERROR: 'MESSAGES_FETCH_CONVERSATIONS_ERROR',
  MESSAGES_FETCH_CONVERSATION_ERROR: 'MESSAGES_FETCH_CONVERSATION_ERROR',
  MESSAGES_CREATE_CONVERSATION_ERROR: 'MESSAGES_CREATE_CONVERSATION_ERROR',
  MESSAGES_UPDATE_CONVERSATION_ERROR: 'MESSAGES_UPDATE_CONVERSATION_ERROR',
  MESSAGES_LEAVE_CONVERSATION_ERROR: 'MESSAGES_LEAVE_CONVERSATION_ERROR',
  MESSAGES_DELETE_CONVERSATION_ERROR: 'MESSAGES_DELETE_CONVERSATION_ERROR',
  MESSAGES_ADD_PARTICIPANTS_ERROR: 'MESSAGES_ADD_PARTICIPANTS_ERROR',
  MESSAGES_REMOVE_PARTICIPANT_ERROR: 'MESSAGES_REMOVE_PARTICIPANT_ERROR',
  MESSAGES_MARK_READ_ERROR: 'MESSAGES_MARK_READ_ERROR',
  MESSAGES_SEARCH_USERS_ERROR: 'MESSAGES_SEARCH_USERS_ERROR',
  MESSAGES_FETCH_MESSAGES_ERROR: 'MESSAGES_FETCH_MESSAGES_ERROR',
  MESSAGES_SEND_MESSAGE_ERROR: 'MESSAGES_SEND_MESSAGE_ERROR',
  MESSAGES_EDIT_MESSAGE_ERROR: 'MESSAGES_EDIT_MESSAGE_ERROR',
  MESSAGES_DELETE_MESSAGE_ERROR: 'MESSAGES_DELETE_MESSAGE_ERROR',
  MESSAGES_FETCH_UNREAD_ERROR: 'MESSAGES_FETCH_UNREAD_ERROR',
  MESSAGES_SEARCH_MESSAGES_ERROR: 'MESSAGES_SEARCH_MESSAGES_ERROR',

  // ============================================================================
  // NOTIFICATIONS MODULE
  // ============================================================================
  NOTIFICATIONS_INVALID_GROUP_ID: 'NOTIFICATIONS_INVALID_GROUP_ID',
  NOTIFICATIONS_INVALID_ID: 'NOTIFICATIONS_INVALID_ID',
  NOTIFICATIONS_MISSING_REQUIRED_FIELDS: 'NOTIFICATIONS_MISSING_REQUIRED_FIELDS',
  NOTIFICATIONS_INVALID_SCHEDULED_DATE: 'NOTIFICATIONS_INVALID_SCHEDULED_DATE',
  NOTIFICATIONS_INVALID_MODULE: 'NOTIFICATIONS_INVALID_MODULE',
  NOTIFICATIONS_NOT_FOUND: 'NOTIFICATIONS_NOT_FOUND',
  NOTIFICATIONS_FETCH_ERROR: 'NOTIFICATIONS_FETCH_ERROR',
  NOTIFICATIONS_FETCH_UNREAD_ERROR: 'NOTIFICATIONS_FETCH_UNREAD_ERROR',
  NOTIFICATIONS_FETCH_COUNT_ERROR: 'NOTIFICATIONS_FETCH_COUNT_ERROR',
  NOTIFICATIONS_PROCESS_ERROR: 'NOTIFICATIONS_PROCESS_ERROR',
  NOTIFICATIONS_FETCH_GROUP_ERROR: 'NOTIFICATIONS_FETCH_GROUP_ERROR',
  NOTIFICATIONS_MARK_READ_ERROR: 'NOTIFICATIONS_MARK_READ_ERROR',
  NOTIFICATIONS_MARK_ERROR: 'NOTIFICATIONS_MARK_ERROR',
  NOTIFICATIONS_MARK_ALL_ERROR: 'NOTIFICATIONS_MARK_ALL_ERROR',
  NOTIFICATIONS_CREATE_ERROR: 'NOTIFICATIONS_CREATE_ERROR',
  NOTIFICATIONS_DELETE_ERROR: 'NOTIFICATIONS_DELETE_ERROR',

  // ============================================================================
  // PARKING MODULE
  // ============================================================================
  PARKING_INVALID_START_DATE: 'PARKING_INVALID_START_DATE',
  PARKING_INVALID_END_DATE: 'PARKING_INVALID_END_DATE',
  PARKING_INVALID_CODE_FORMAT: 'PARKING_INVALID_CODE_FORMAT',
  PARKING_INVALID_DATE_FORMAT: 'PARKING_INVALID_DATE_FORMAT',
  PARKING_END_BEFORE_START: 'PARKING_END_BEFORE_START',
  PARKING_INVALID_AMOUNT: 'PARKING_INVALID_AMOUNT',
  PARKING_NO_FIELDS_TO_UPDATE: 'PARKING_NO_FIELDS_TO_UPDATE',
  PARKING_CANNOT_UPDATE_STATUS: 'PARKING_CANNOT_UPDATE_STATUS',
  PARKING_CANNOT_DELETE_STATUS: 'PARKING_CANNOT_DELETE_STATUS',
  PARKING_CANNOT_DELETE_STARTED: 'PARKING_CANNOT_DELETE_STARTED',
  PARKING_BOOKING_NOT_FOUND: 'PARKING_BOOKING_NOT_FOUND',
  PARKING_FETCH_BOOKINGS_ERROR: 'PARKING_FETCH_BOOKINGS_ERROR',
  PARKING_FETCH_BOOKING_ERROR: 'PARKING_FETCH_BOOKING_ERROR',
  PARKING_CREATE_BOOKING_ERROR: 'PARKING_CREATE_BOOKING_ERROR',
  PARKING_CHECKIN_ERROR: 'PARKING_CHECKIN_ERROR',
  PARKING_CHECKOUT_ERROR: 'PARKING_CHECKOUT_ERROR',
  PARKING_CANCEL_ERROR: 'PARKING_CANCEL_ERROR',
  PARKING_NOSHOW_ERROR: 'PARKING_NOSHOW_ERROR',
  PARKING_UPDATE_BOOKING_ERROR: 'PARKING_UPDATE_BOOKING_ERROR',
  PARKING_DELETE_BOOKING_ERROR: 'PARKING_DELETE_BOOKING_ERROR',
  PARKING_FETCH_DELAYED_ERROR: 'PARKING_FETCH_DELAYED_ERROR',
  PARKING_INVALID_DATE: 'PARKING_INVALID_DATE',
  PARKING_DATE_RANGE_REQUIRED: 'PARKING_DATE_RANGE_REQUIRED',
  PARKING_START_BEFORE_END: 'PARKING_START_BEFORE_END',
  PARKING_INVALID_DATES: 'PARKING_INVALID_DATES',
  PARKING_COMPARISON_DATES_REQUIRED: 'PARKING_COMPARISON_DATES_REQUIRED',
  PARKING_FETCH_STATS_ERROR: 'PARKING_FETCH_STATS_ERROR',
  PARKING_FETCH_OCCUPANCY_ERROR: 'PARKING_FETCH_OCCUPANCY_ERROR',
  PARKING_FETCH_PENDING_CHECKINS_ERROR: 'PARKING_FETCH_PENDING_CHECKINS_ERROR',
  PARKING_FETCH_PENDING_CHECKOUTS_ERROR: 'PARKING_FETCH_PENDING_CHECKOUTS_ERROR',
  PARKING_FETCH_AVAILABILITY_ERROR: 'PARKING_FETCH_AVAILABILITY_ERROR',
  PARKING_FETCH_DASHBOARD_ERROR: 'PARKING_FETCH_DASHBOARD_ERROR',
  PARKING_FETCH_RANGE_STATS_ERROR: 'PARKING_FETCH_RANGE_STATS_ERROR',
  PARKING_FETCH_RANGE_OCCUPANCY_ERROR: 'PARKING_FETCH_RANGE_OCCUPANCY_ERROR',
  PARKING_FETCH_TRENDS_ERROR: 'PARKING_FETCH_TRENDS_ERROR',
  PARKING_COMPARE_PERIODS_ERROR: 'PARKING_COMPARE_PERIODS_ERROR',
  PARKING_FETCH_PERFORMANCE_ERROR: 'PARKING_FETCH_PERFORMANCE_ERROR',
  PARKING_ANALYZE_BOOKINGS_ERROR: 'PARKING_ANALYZE_BOOKINGS_ERROR',

  // ============================================================================
  // ACTIVITY MODULE
  // ============================================================================
  ACTIVITY_INVALID_SOURCE: 'ACTIVITY_INVALID_SOURCE',
  ACTIVITY_INVALID_DATE_FORMAT: 'ACTIVITY_INVALID_DATE_FORMAT',
  ACTIVITY_FETCH_ERROR: 'ACTIVITY_FETCH_ERROR',
} as const

// Type for error codes
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

// ============================================================================
// SUCCESS CODES (for messages that need translation too)
// ============================================================================
export const SUCCESS_CODES = {
  // Auth
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_PROFILE_UPDATED: 'AUTH_PROFILE_UPDATED',
  AUTH_PASSWORD_UPDATED: 'AUTH_PASSWORD_UPDATED',
  AUTH_AVATAR_UPDATED: 'AUTH_AVATAR_UPDATED',
  AUTH_AVATAR_DELETED: 'AUTH_AVATAR_DELETED',
  AUTH_USER_DELETED: 'AUTH_USER_DELETED',

  // Backoffice
  BACKOFFICE_CATEGORY_CREATED: 'BACKOFFICE_CATEGORY_CREATED',
  BACKOFFICE_SUPPLIER_CREATED: 'BACKOFFICE_SUPPLIER_CREATED',
  BACKOFFICE_SUPPLIER_UPDATED: 'BACKOFFICE_SUPPLIER_UPDATED',
  BACKOFFICE_SUPPLIER_DEACTIVATED: 'BACKOFFICE_SUPPLIER_DEACTIVATED',
  BACKOFFICE_SUPPLIER_INACTIVATED: 'BACKOFFICE_SUPPLIER_INACTIVATED',
  BACKOFFICE_SUPPLIER_ACTIVATED: 'BACKOFFICE_SUPPLIER_ACTIVATED',
  BACKOFFICE_SUPPLIER_DELETED: 'BACKOFFICE_SUPPLIER_DELETED',
  BACKOFFICE_INVOICE_CREATED: 'BACKOFFICE_INVOICE_CREATED',
  BACKOFFICE_INVOICE_UPDATED: 'BACKOFFICE_INVOICE_UPDATED',
  BACKOFFICE_INVOICE_VALIDATED: 'BACKOFFICE_INVOICE_VALIDATED',
  BACKOFFICE_INVOICE_REJECTED: 'BACKOFFICE_INVOICE_REJECTED',
  BACKOFFICE_VALIDATION_REVERTED: 'BACKOFFICE_VALIDATION_REVERTED',
  BACKOFFICE_INVOICE_PAID: 'BACKOFFICE_INVOICE_PAID',
  BACKOFFICE_INVOICE_DELETED: 'BACKOFFICE_INVOICE_DELETED',
  BACKOFFICE_PDF_UPLOADED: 'BACKOFFICE_PDF_UPLOADED',
  BACKOFFICE_ASSET_CREATED: 'BACKOFFICE_ASSET_CREATED',
  BACKOFFICE_ASSET_DELETED: 'BACKOFFICE_ASSET_DELETED',
  BACKOFFICE_ASSET_DEFAULT_SET: 'BACKOFFICE_ASSET_DEFAULT_SET',

  // Blacklist
  BLACKLIST_RECORD_CREATED: 'BLACKLIST_RECORD_CREATED',
  BLACKLIST_RECORD_UPDATED: 'BLACKLIST_RECORD_UPDATED',
  BLACKLIST_RECORD_DELETED: 'BLACKLIST_RECORD_DELETED',
  BLACKLIST_RECORD_RESTORED: 'BLACKLIST_RECORD_RESTORED',
  BLACKLIST_IMAGE_DELETED: 'BLACKLIST_IMAGE_DELETED',

  // Cashier
  CASHIER_DAY_INITIALIZED: 'CASHIER_DAY_INITIALIZED',
  CASHIER_DAY_CLOSED: 'CASHIER_DAY_CLOSED',
  CASHIER_DAY_REOPENED: 'CASHIER_DAY_REOPENED',
  CASHIER_SHIFT_DELETED: 'CASHIER_SHIFT_DELETED',
  CASHIER_PAYMENT_DELETED: 'CASHIER_PAYMENT_DELETED',
  CASHIER_VOUCHER_DELETED: 'CASHIER_VOUCHER_DELETED',
  CASHIER_DENOMINATION_DELETED: 'CASHIER_DENOMINATION_DELETED',

  // Conciliation
  CONCILIATION_CREATED: 'CONCILIATION_CREATED',
  CONCILIATION_FORM_UPDATED: 'CONCILIATION_FORM_UPDATED',
  CONCILIATION_TOTALS_RECALCULATED: 'CONCILIATION_TOTALS_RECALCULATED',
  CONCILIATION_DELETED: 'CONCILIATION_DELETED',

  // Departments
  DEPARTMENTS_DELETED: 'DEPARTMENTS_DELETED',

  // Group
  GROUP_CREATED: 'GROUP_CREATED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  GROUP_DELETED: 'GROUP_DELETED',
  GROUP_CONTACT_CREATED: 'GROUP_CONTACT_CREATED',
  GROUP_CONTACT_UPDATED: 'GROUP_CONTACT_UPDATED',
  GROUP_CONTACT_DELETED: 'GROUP_CONTACT_DELETED',
  GROUP_ROOM_SAVED: 'GROUP_ROOM_SAVED',
  GROUP_ROOM_UPDATED: 'GROUP_ROOM_UPDATED',
  GROUP_ROOM_DELETED: 'GROUP_ROOM_DELETED',
  GROUP_PAYMENT_CREATED: 'GROUP_PAYMENT_CREATED',
  GROUP_PAYMENT_UPDATED: 'GROUP_PAYMENT_UPDATED',
  GROUP_PAYMENT_DELETED: 'GROUP_PAYMENT_DELETED',
  GROUP_BOOKING_UPDATED: 'GROUP_BOOKING_UPDATED',
  GROUP_CONTRACT_UPDATED: 'GROUP_CONTRACT_UPDATED',
  GROUP_ROOMING_UPDATED: 'GROUP_ROOMING_UPDATED',
  GROUP_BALANCE_UPDATED: 'GROUP_BALANCE_UPDATED',

  // Logbook
  LOGBOOK_UPDATED: 'LOGBOOK_UPDATED',
  LOGBOOK_DELETED: 'LOGBOOK_DELETED',
  LOGBOOK_READ_SUCCESS: 'LOGBOOK_READ_SUCCESS',
  LOGBOOK_UNREAD_SUCCESS: 'LOGBOOK_UNREAD_SUCCESS',
  LOGBOOK_SOLVED_SUCCESS: 'LOGBOOK_SOLVED_SUCCESS',
  LOGBOOK_REOPENED_SUCCESS: 'LOGBOOK_REOPENED_SUCCESS',
  LOGBOOK_COMMENT_UPDATED: 'LOGBOOK_COMMENT_UPDATED',
  LOGBOOK_COMMENT_DELETED: 'LOGBOOK_COMMENT_DELETED',

  // Maintenance
  MAINTENANCE_REPORT_CREATED: 'MAINTENANCE_REPORT_CREATED',
  MAINTENANCE_REPORT_UPDATED: 'MAINTENANCE_REPORT_UPDATED',
  MAINTENANCE_STATUS_UPDATED: 'MAINTENANCE_STATUS_UPDATED',
  MAINTENANCE_PRIORITY_UPDATED: 'MAINTENANCE_PRIORITY_UPDATED',
  MAINTENANCE_NOTES_ADDED: 'MAINTENANCE_NOTES_ADDED',
  MAINTENANCE_REPORT_ASSIGNED: 'MAINTENANCE_REPORT_ASSIGNED',
  MAINTENANCE_REPORT_DELETED: 'MAINTENANCE_REPORT_DELETED',
  MAINTENANCE_REPORT_RESTORED: 'MAINTENANCE_REPORT_RESTORED',
  MAINTENANCE_IMAGE_UPLOADED: 'MAINTENANCE_IMAGE_UPLOADED',
  MAINTENANCE_IMAGE_DELETED: 'MAINTENANCE_IMAGE_DELETED',

  // Messages
  MESSAGES_DM_EXISTS: 'MESSAGES_DM_EXISTS',
  MESSAGES_GROUP_UPDATED: 'MESSAGES_GROUP_UPDATED',
  MESSAGES_LEFT_CONVERSATION: 'MESSAGES_LEFT_CONVERSATION',
  MESSAGES_CONVERSATION_DELETED: 'MESSAGES_CONVERSATION_DELETED',
  MESSAGES_PARTICIPANTS_ADDED: 'MESSAGES_PARTICIPANTS_ADDED',
  MESSAGES_PARTICIPANT_REMOVED: 'MESSAGES_PARTICIPANT_REMOVED',
  MESSAGES_MARKED_READ: 'MESSAGES_MARKED_READ',
  MESSAGES_SENT: 'MESSAGES_SENT',
  MESSAGES_EDITED: 'MESSAGES_EDITED',
  MESSAGES_DELETED: 'MESSAGES_DELETED',

  // Notifications
  NOTIFICATIONS_PROCESSED: 'NOTIFICATIONS_PROCESSED',
  NOTIFICATIONS_MARKED_READ: 'NOTIFICATIONS_MARKED_READ',
  NOTIFICATIONS_ALL_MARKED_READ: 'NOTIFICATIONS_ALL_MARKED_READ',
  NOTIFICATIONS_CREATED: 'NOTIFICATIONS_CREATED',
  NOTIFICATIONS_DELETED: 'NOTIFICATIONS_DELETED',

  // Parking
  PARKING_BOOKING_CREATED: 'PARKING_BOOKING_CREATED',
  PARKING_CHECKIN_SUCCESS: 'PARKING_CHECKIN_SUCCESS',
  PARKING_CHECKOUT_SUCCESS: 'PARKING_CHECKOUT_SUCCESS',
  PARKING_BOOKING_CANCELLED: 'PARKING_BOOKING_CANCELLED',
  PARKING_NOSHOW_SUCCESS: 'PARKING_NOSHOW_SUCCESS',
  PARKING_BOOKING_UPDATED: 'PARKING_BOOKING_UPDATED',
  PARKING_BOOKING_DELETED: 'PARKING_BOOKING_DELETED',
} as const

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES]
