// app/lib/maintenance/maintenance-mock.ts

import { v4 as uuidv4 } from 'uuid'
import type {
  MaintenanceReport,
  MaintenanceImage,
  MaintenanceHistory,
  ReportWithDetails,
} from '@/app/lib/maintenance/maintenance'

const MOCK_USER_IDS = {
  admin: '550e8400-e29b-41d4-a716-446655440000',
  maintenance: '550e8400-e29b-41d4-a716-446655440001',
  reception: '550e8400-e29b-41d4-a716-446655440002',
  housekeeping: '550e8400-e29b-41d4-a716-446655440003',
}

const MOCK_USERS = {
  [MOCK_USER_IDS.admin]: 'Salvador Pérez',
  [MOCK_USER_IDS.maintenance]: 'Juan García',
  [MOCK_USER_IDS.reception]: 'María López',
  [MOCK_USER_IDS.housekeeping]: 'Ana Martínez',
}

export const mockReports: MaintenanceReport[] = [
  {
    id: uuidv4(),
    report_date: '2024-11-28T09:30:00Z',
    location_type: 'room',
    location_description: 'Habitación 305 - Baño',
    title: 'Fuga de agua en grifo del lavabo',
    description:
      'Cliente reporta que el grifo del lavabo gotea constantemente. Se observa humedad en la base.',
    priority: 'urgent',
    status: 'in_progress',
    room_number: '305',
    room_out_of_service: true,
    assigned_to: MOCK_USER_IDS.maintenance,
    assigned_type: 'internal',
    external_company_name: null,
    external_contact: null,
    started_at: '2024-11-28T10:00:00Z',
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-28T09:30:00Z',
    updated_by: MOCK_USER_IDS.maintenance,
    updated_at: '2024-11-28T10:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-27T14:15:00Z',
    location_type: 'common_area',
    location_description: 'Lobby principal - Aire acondicionado',
    title: 'Sistema de climatización no enfría',
    description:
      'El aire acondicionado del lobby no está enfriando adecuadamente. Temperatura ambiente 28°C.',
    priority: 'high',
    status: 'assigned',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: 'external',
    external_company_name: 'Climatización Industrial S.L.',
    external_contact: '+34 600 123 456 - Pedro Ramírez',
    started_at: null,
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-27T14:15:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-27T15:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-26T11:00:00Z',
    location_type: 'room',
    location_description: 'Habitación 412 - TV',
    title: 'Televisor no enciende',
    description:
      'El cliente reporta que la TV no responde al control remoto ni a los botones físicos.',
    priority: 'medium',
    status: 'completed',
    room_number: '412',
    room_out_of_service: false,
    assigned_to: MOCK_USER_IDS.maintenance,
    assigned_type: 'internal',
    external_company_name: null,
    external_contact: null,
    started_at: '2024-11-26T12:00:00Z',
    resolved_at: '2024-11-26T13:30:00Z',
    closed_at: null,
    resolution_notes: 'TV reemplazada por unidad nueva. TV antigua enviada a reparación.',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.housekeeping,
    created_at: '2024-11-26T11:00:00Z',
    updated_by: MOCK_USER_IDS.maintenance,
    updated_at: '2024-11-26T13:30:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-25T16:45:00Z',
    location_type: 'exterior',
    location_description: 'Parking exterior - Iluminación zona norte',
    title: 'Farolas del parking no funcionan',
    description:
      'Varias farolas del parking exterior no encienden por la noche. Afecta aprox. 15 plazas.',
    priority: 'high',
    status: 'closed',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: 'external',
    external_company_name: 'Electricidad Martínez e Hijos',
    external_contact: '+34 610 987 654 - Carlos Martínez',
    started_at: '2024-11-26T09:00:00Z',
    resolved_at: '2024-11-26T14:00:00Z',
    closed_at: '2024-11-26T15:00:00Z',
    resolution_notes:
      'Reemplazadas 6 luminarias LED. Problema era cableado deteriorado en caja de conexiones.',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-25T16:45:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-26T15:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-28T08:00:00Z',
    location_type: 'room',
    location_description: 'Habitación 201 - Persiana',
    title: 'Persiana eléctrica atascada',
    description: 'La persiana de la habitación no sube ni baja. Motor hace ruido extraño.',
    priority: 'medium',
    status: 'waiting',
    room_number: '201',
    room_out_of_service: false,
    assigned_to: MOCK_USER_IDS.maintenance,
    assigned_type: 'internal',
    external_company_name: null,
    external_contact: null,
    started_at: '2024-11-28T09:00:00Z',
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.housekeeping,
    created_at: '2024-11-28T08:00:00Z',
    updated_by: MOCK_USER_IDS.maintenance,
    updated_at: '2024-11-28T09:15:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-27T19:30:00Z',
    location_type: 'facilities',
    location_description: 'Gimnasio - Cinta de correr #2',
    title: 'Cinta de correr con error en pantalla',
    description: 'La cinta de correr número 2 muestra error E07 y no arranca.',
    priority: 'low',
    status: 'reported',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: null,
    external_company_name: null,
    external_contact: null,
    started_at: null,
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-27T19:30:00Z',
    updated_by: null,
    updated_at: '2024-11-27T19:30:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-24T10:00:00Z',
    location_type: 'room',
    location_description: 'Habitación 508 - Cerradura',
    title: 'Cerradura de puerta no responde a tarjeta',
    description:
      'El sistema de cerradura electrónica no lee las tarjetas. Cliente tuvo que pedir llave maestra.',
    priority: 'urgent',
    status: 'closed',
    room_number: '508',
    room_out_of_service: true,
    assigned_to: MOCK_USER_IDS.maintenance,
    assigned_type: 'internal',
    external_company_name: null,
    external_contact: null,
    started_at: '2024-11-24T10:30:00Z',
    resolved_at: '2024-11-24T12:00:00Z',
    closed_at: '2024-11-24T14:00:00Z',
    resolution_notes: 'Batería del lector agotada. Reemplazada y reprogramada cerradura.',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-24T10:00:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-24T14:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-28T07:15:00Z',
    location_type: 'common_area',
    location_description: 'Comedor principal - Ventana este',
    title: 'Cristal roto en ventana del comedor',
    description:
      'Se detectó un cristal agrietado en la ventana este del comedor. No es urgente pero debe repararse.',
    priority: 'medium',
    status: 'assigned',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: 'external',
    external_company_name: 'Cristalería Moderna',
    external_contact: '+34 620 555 777 - Luis Fernández',
    started_at: null,
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.housekeeping,
    created_at: '2024-11-28T07:15:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-28T08:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-26T15:00:00Z',
    location_type: 'other',
    location_description: 'Lavandería - Secadora industrial #1',
    title: 'Secadora no calienta',
    description: 'La secadora industrial #1 gira pero no calienta. Ropa sale húmeda.',
    priority: 'high',
    status: 'in_progress',
    room_number: null,
    room_out_of_service: null,
    assigned_to: MOCK_USER_IDS.maintenance,
    assigned_type: 'internal',
    external_company_name: null,
    external_contact: null,
    started_at: '2024-11-26T16:00:00Z',
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.housekeeping,
    created_at: '2024-11-26T15:00:00Z',
    updated_by: MOCK_USER_IDS.maintenance,
    updated_at: '2024-11-26T16:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-23T12:00:00Z',
    location_type: 'room',
    location_description: 'Habitación 310 - Duplicado',
    title: 'Reporte duplicado - Cerrado',
    description: 'Este reporte era un duplicado del reporte anterior sobre la misma incidencia.',
    priority: 'low',
    status: 'canceled',
    room_number: '310',
    room_out_of_service: false,
    assigned_to: null,
    assigned_type: null,
    external_company_name: null,
    external_contact: null,
    started_at: null,
    resolved_at: null,
    closed_at: '2024-11-23T13:00:00Z',
    resolution_notes: 'Cancelado por duplicidad.',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-23T12:00:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-23T13:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-27T10:30:00Z',
    location_type: 'room',
    location_description: 'Habitación 215 - Caja fuerte',
    title: 'Caja fuerte bloqueada',
    description: 'Cliente olvidó código de caja fuerte. Requiere reset.',
    priority: 'medium',
    status: 'completed',
    room_number: '215',
    room_out_of_service: false,
    assigned_to: MOCK_USER_IDS.maintenance,
    assigned_type: 'internal',
    external_company_name: null,
    external_contact: null,
    started_at: '2024-11-27T11:00:00Z',
    resolved_at: '2024-11-27T11:30:00Z',
    closed_at: null,
    resolution_notes: 'Reset realizado con código maestro. Cliente informado.',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-27T10:30:00Z',
    updated_by: MOCK_USER_IDS.maintenance,
    updated_at: '2024-11-27T11:30:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-28T06:00:00Z',
    location_type: 'exterior',
    location_description: 'Piscina exterior - Sistema de filtrado',
    title: 'Bomba de piscina hace ruido anormal',
    description:
      'La bomba de filtrado de la piscina hace un ruido metálico. Posible problema en rodamientos.',
    priority: 'high',
    status: 'reported',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: null,
    external_company_name: null,
    external_contact: null,
    started_at: null,
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.maintenance,
    created_at: '2024-11-28T06:00:00Z',
    updated_by: null,
    updated_at: '2024-11-28T06:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-25T14:00:00Z',
    location_type: 'facilities',
    location_description: 'Sauna - Termostato',
    title: 'Sauna no alcanza temperatura',
    description: 'La sauna tarda más de 2 horas en alcanzar 80°C. Antes tardaba 45 minutos.',
    priority: 'medium',
    status: 'waiting',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: 'external',
    external_company_name: 'Termoequipos S.A.',
    external_contact: '+34 655 444 333 - Roberto Díaz',
    started_at: '2024-11-26T10:00:00Z',
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-25T14:00:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-26T10:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-22T09:00:00Z',
    location_type: 'common_area',
    location_description: 'Recepción - Puerta automática',
    title: 'Puerta automática no cierra completamente',
    description:
      'La puerta automática de la entrada principal no cierra del todo. Queda un espacio de 2-3 cm.',
    priority: 'urgent',
    status: 'closed',
    room_number: null,
    room_out_of_service: null,
    assigned_to: null,
    assigned_type: 'external',
    external_company_name: 'Puertas Automáticas del Sur',
    external_contact: '+34 600 111 222 - Alberto Ruiz',
    started_at: '2024-11-22T11:00:00Z',
    resolved_at: '2024-11-22T15:00:00Z',
    closed_at: '2024-11-22T16:00:00Z',
    resolution_notes: 'Sensor desalineado. Ajustado y calibrado sistema completo.',
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.reception,
    created_at: '2024-11-22T09:00:00Z',
    updated_by: MOCK_USER_IDS.admin,
    updated_at: '2024-11-22T16:00:00Z',
  },
  {
    id: uuidv4(),
    report_date: '2024-11-28T05:30:00Z',
    location_type: 'room',
    location_description: 'Habitación 101 - Minibar',
    title: 'Minibar no enfría',
    description: 'El minibar de la habitación no mantiene temperatura. Bebidas están templadas.',
    priority: 'low',
    status: 'reported',
    room_number: '101',
    room_out_of_service: false,
    assigned_to: null,
    assigned_type: null,
    external_company_name: null,
    external_contact: null,
    started_at: null,
    resolved_at: null,
    closed_at: null,
    resolution_notes: null,
    is_deleted: false,
    deleted_at: null,
    deleted_by: null,
    created_by: MOCK_USER_IDS.housekeeping,
    created_at: '2024-11-28T05:30:00Z',
    updated_by: null,
    updated_at: '2024-11-28T05:30:00Z',
  },
]

export const mockImages: Record<string, MaintenanceImage[]> = {}
export const mockHistory: Record<string, MaintenanceHistory[]> = {}

// Generar historial mock para cada reporte
mockReports.forEach((report) => {
  const history: MaintenanceHistory[] = [
    {
      id: 1,
      report_id: report.id,
      action: 'created',
      field_changed: null,
      old_value: null,
      new_value: null,
      notes: `Reporte creado: ${report.title}`,
      changed_by: report.created_by,
      changed_at: report.created_at,
      user_name: MOCK_USERS[report.created_by as keyof typeof MOCK_USERS],
    },
  ]

  let historyId = 2

  if (report.status !== 'reported') {
    history.push({
      id: historyId++,
      report_id: report.id,
      action: 'assigned',
      field_changed: 'assigned_to',
      old_value: null,
      new_value: report.assigned_to || report.external_company_name || '',
      notes:
        report.assigned_type === 'external'
          ? `Asignado a empresa externa: ${report.external_company_name}`
          : `Asignado a: ${MOCK_USERS[report.assigned_to as keyof typeof MOCK_USERS] || 'Usuario'}`,
      changed_by: report.updated_by || report.created_by,
      changed_at: new Date(new Date(report.created_at).getTime() + 1800000).toISOString(),
      user_name:
        MOCK_USERS[report.updated_by as keyof typeof MOCK_USERS] ||
        MOCK_USERS[report.created_by as keyof typeof MOCK_USERS],
    })
  }

  if (report.started_at) {
    history.push({
      id: historyId++,
      report_id: report.id,
      action: 'status_changed',
      field_changed: 'status',
      old_value: 'assigned',
      new_value: 'in_progress',
      notes: 'Trabajo iniciado',
      changed_by: report.assigned_to || report.created_by,
      changed_at: report.started_at,
      user_name: MOCK_USERS[report.assigned_to as keyof typeof MOCK_USERS] || 'Usuario',
    })
  }

  if (report.status === 'waiting') {
    history.push({
      id: historyId++,
      report_id: report.id,
      action: 'status_changed',
      field_changed: 'status',
      old_value: 'in_progress',
      new_value: 'waiting',
      notes: 'En espera de material/autorización',
      changed_by: report.assigned_to || report.created_by,
      changed_at: new Date(
        new Date(report.started_at || report.created_at).getTime() + 3600000
      ).toISOString(),
      user_name: MOCK_USERS[report.assigned_to as keyof typeof MOCK_USERS] || 'Usuario',
    })
  }

  if (report.resolved_at) {
    history.push({
      id: historyId++,
      report_id: report.id,
      action: 'resolved',
      field_changed: 'status',
      old_value: 'in_progress',
      new_value: 'completed',
      notes: report.resolution_notes || 'Trabajo completado',
      changed_by: report.assigned_to || report.created_by,
      changed_at: report.resolved_at,
      user_name: MOCK_USERS[report.assigned_to as keyof typeof MOCK_USERS] || 'Usuario',
    })
  }

  if (report.closed_at) {
    history.push({
      id: historyId++,
      report_id: report.id,
      action: 'closed',
      field_changed: 'status',
      old_value: report.status === 'canceled' ? 'reported' : 'completed',
      new_value: report.status,
      notes:
        report.status === 'canceled'
          ? report.resolution_notes || 'Reporte cancelado'
          : 'Reporte cerrado y verificado',
      changed_by: report.updated_by || MOCK_USER_IDS.admin,
      changed_at: report.closed_at,
      user_name:
        MOCK_USERS[report.updated_by as keyof typeof MOCK_USERS] || MOCK_USERS[MOCK_USER_IDS.admin],
    })
  }

  mockHistory[report.id] = history
})

export { MOCK_USERS, MOCK_USER_IDS }
